### ISSUE TITLE
Escaped quotes

### ISSUE THREAD

**Issue by KindDragon** [pektin/jam-sublime-syntax#2]
Hi. Ty for plugin, but it doesn't work for some cases:

```
check-equal normalize-path : "/"     : [ NORMALIZE_PATH "/" ] ;
check-equal normalize-path : "/"     : [ NORMALIZE_PATH "\\" ] ;
check-equal normalize-path : "/"     : [ NORMALIZE_PATH "//" ] ;
check-equal normalize-path : "/"     : [ NORMALIZE_PATH "\\\\" ] ;
```
https://github.com/boostorg/build/blob/develop/test/core-language/test.jam

**Comment by BenjaminSchaaf** [comment]
Sorry for the confusion, but this is not for Boost.Jam Language but for the [Jam Programming Language](https://lets-jam.org)
